#!/bin/sh

echo "Mac web development setup helper"
echo ""
echo "Machine snapshot:"
echo "  macOS: 15.7.2"
echo "  CPU: x86_64"
echo ""
echo "What is missing right now:"
echo "  - Apple command line developer tools"
echo "  - Homebrew"
echo "  - Git"
echo "  - Node.js and npm"
echo ""
echo "Step 1: Install Apple command line developer tools"
echo "  Run this in Terminal from a normal desktop session:"
echo "  xcode-select --install"
echo ""
echo "Step 2: Install Homebrew"
echo "  After step 1 finishes, run:"
echo "  /bin/bash -c \"\$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""
echo ""
echo "Step 3: Install Git and Node.js"
echo "  If brew installs to /usr/local/bin, run:"
echo "  brew install git node"
echo ""
echo "Step 4: Verify"
echo "  git --version"
echo "  node -v"
echo "  npm -v"
echo ""
echo "Step 5: Come back here and we can scaffold a React or Next.js app."
